targets:
  $default:
    auto_apply_builders: true
    builders:
      catalyst_builder|preflight:
        options:
          generatedProviderFile: 'lib/example.catalyst_builder.g.dart'
      catalyst_builder|buildServiceProvider:
        options:
          providerClassName: 'ExampleProvider'
          includePackageDependencies: true
