name: catalyst_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  catalyst_builder:
    path: ../

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: ^2.0.1
