name: di_experimental_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  di_experimental:
    path: ../

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: ^1.12.2
