name: catalyst_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  catalyst_builder:
    path: ../
  third_party_dependency:
    path: ../test/third_party_dependency

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.0.1
