name: catalyst_builder_contracts_example
description: The example application for catalyst_builder_contracts
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  catalyst_builder_contracts:
  catalyst_builder_container:

dev_dependencies:
  build_runner:
  catalyst_builder:

dependency_overrides:
  catalyst_builder_contracts:
    path: ../../catalyst_builder_contracts
  catalyst_builder:
    path: ../../catalyst_builder
  catalyst_builder_container:
    path: ../
