builders:
  preflight:
    import: 'package:catalyst_builder/src/builder/preflight_builder.dart'
    builder_factories:
      - 'runPreflight'
    build_extensions: { '.dart': [ '.catalyst_builder.preflight.json' ] }
    build_to: cache
    auto_apply: dependents

  buildServiceProvider:
    import: 'package:catalyst_builder/src/builder/service_provider_builder.dart'
    builder_factories:
      - 'buildServiceProvider'
    build_extensions: { '.dart': [ '.catalyst_builder.g.dart' ] }
    build_to: source
    auto_apply: dependents
    required_inputs:
      - '.catalyst_builder.preflight.json'
    defaults:
      options:
        providerClassName: 'DefaultServiceProvider'
        includePackageDependencies: false
