name: catalyst_builder
description: A dependency injection provider builder for dart. Easy to use and lightweight af.
version: 0.0.2
homepage: 'https://www.mintware.de/'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  code_builder: ^3.7.0
  dart_style: ^2.0.0
  build: ^2.0.0
  glob: ^2.0.0
  path: ^1.8.0
  analyzer: ^1.4.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^1.12.2
  source_gen: ^1.0.0
  effective_dart: ^1.3.1