name: catalyst_builder
description: A dependency injection provider builder for dart. Easy to use and lightweight af.
version: 1.3.2
homepage: 'https://github.com/mintware-de/catalyst_builder'
repository: 'https://github.com/mintware-de/catalyst_builder'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  code_builder: ^4.1.0
  dart_style: ^2.0.1
  build: ^2.1.0
  glob: ^2.0.1
  path: ^1.8.0
  build_runner_core: ^7.1.0

dev_dependencies:
  test: ^1.17.8
  build_runner: ^2.0.4
  source_gen: ^1.0.2
  effective_dart: ^1.3.1
