name: catalyst_builder
description: A lightweight and easy to use dependency injection provider builder for dart.
version: 4.0.0
homepage: 'https://github.com/mintware-de/catalyst_builder'
repository: 'https://github.com/mintware-de/catalyst_builder'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  code_builder: ^4.2.0
  dart_style: ^3.0.1
  build: ^2.1.0
  glob: ^2.1.0
  path: ^1.8.0
  analyzer: '>=6.2.0 <8.0.0'

dev_dependencies:
  test: any
  lints: any
  build_runner: ^2.2.0
