name: catalyst_builder
description: A dependency injection provider builder for dart. Easy to use and lightweight af.
version: 2.3.1
homepage: 'https://github.com/mintware-de/catalyst_builder'
repository: 'https://github.com/mintware-de/catalyst_builder'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  code_builder: ^4.1.0
  dart_style: ^2.0.1
  build: ^2.1.0
  glob: ^2.1.0
  path: ^1.8.0
  analyzer: '>=4.3.0 <5.0.0'
  build_runner_core: ^7.1.0

dev_dependencies:
  test: any
  build_runner: ^2.2.0
  lints: ^2.0.0
