name: catalyst_builder
description: A dependency injection provider builder for dart. Easy to use and lightweight af.
version: 0.0.6
homepage: 'https://www.mintware.de/'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  build: ^2.0.1
  glob: ^2.0.1
  path: ^1.8.0
  analyzer: ^1.5.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.7
  build_runner: ^2.0.1
  source_gen: ^1.0.0
  effective_dart: ^1.3.1
