name: di_experimental
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build: ^2.0.0
  build_runner: ^1.12.2
  source_gen: ^1.0.0
  code_builder: ^3.7.0
  dart_style: ^2.0.0