name: catalyst_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  catalyst_builder:
    path: ../
  third_party_dependency:
    path: ../test/third_party_dependency

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.0.1

catalyst_builder:
  cacheDir: '.cache/catalyst_builder'