name: catalyst_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  catalyst_builder_contracts:
    path: ../../catalyst_builder_contracts
  third_party_dependency:
    path: ../test/third_party_dependency
  catalyst_builder_container:
    path: ../../catalyst_builder_container

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.0.1
  catalyst_builder:
    path: ../

dependency_overrides:
  catalyst_builder:
    path: ../
  catalyst_builder_contracts:
    path: ../../catalyst_builder_contracts
  catalyst_builder_container:
    path: ../../catalyst_builder_container