name: catalyst_builder_contracts
description: This is the contracts package for the catalyst_builder package. It includes annotations and marker interfaces.
version: 2.0.0-rc.1
homepage: 'https://github.com/mintware-de/catalyst_builder'
repository: 'https://github.com/mintware-de/catalyst_builder/tree/main/packages/catalyst_builder_contracts'
documentation: https://github.com/mintware-de/catalyst_builder/wiki
issue_tracker: https://github.com/mintware-de/catalyst_builder/issues?q=is%3Aopen+label%3Acatalyst_builder_contracts
funding:
  - https://github.com/sponsors/mintware-de

topics:
  - code-generation
  - builder
  - dependency-injection
  - annotations
  - service-provider

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  test: any
  lints: any
