name: catalyst_builder_contracts
description: This is the contracts package for the catalyst_builder package. It includes annotations and marker interfaces.
version: 0.0.2
homepage: 'https://github.com/mintware-de/catalyst_builder'
repository: 'https://github.com/mintware-de/catalyst_builder/packages/catalyst_builder_contracts'
documentation: https://github.com/mintware-de/catalyst_builder/wiki

topics:
  - code-generation
  - builder
  - dependency-injection
  - annotations
  - service-provider

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  test: any
  lints: any
