builders:
  entrypoint:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factories:
      - 'createEntrypointBuilder'
    build_extensions:
      '.dart': [ '.catalyst_builder.entrypoint.json' ]
    build_to: cache
    auto_apply: root_package
  preflight:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factories:
      - 'createPreflightBuilder'
    build_extensions:
      '.dart': [ '.catalyst_builder.preflight.json' ]
    build_to: cache
    auto_apply: all_packages
    required_inputs:
      - '.catalyst_builder.entrypoint.json'
  buildServiceProvider:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factories:
      - 'createServiceProviderBuilder'
    build_extensions:
      '.catalyst_builder.entrypoint.json': [ '.catalyst_builder.g.dart' ]
    build_to: source
    auto_apply: root_package
    required_inputs:
      - '.catalyst_builder.entrypoint.json'


