builders:
  entrypoint:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factories:
      - 'createEntrypointBuilder'
    build_extensions:
      '.dart': [ '.catalyst_builder.entrypoint.json' ]
    build_to: cache
    auto_apply: root_package
    runs_before:
      - 'catalyst_builder:preflight'
  preflight:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factories:
      - 'createPreflightBuilder'
    build_extensions:
      '.dart': [ '.catalyst_builder.preflight.json' ]
    build_to: cache
    auto_apply: all_packages
    required_inputs:
      - '.catalyst_builder.entrypoint.json'
    applies_builders:
      - 'catalyst_builder:buildServiceProvider'
post_process_builders:
  buildServiceProvider:
    import: 'package:catalyst_builder/src/builder/builders.dart'
    builder_factory: 'createServiceProviderBuilder'
    input_extensions: [".catalyst_builder.entrypoint.json", '.catalyst_builder.preflight.json']