name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: dart analyze lib

      - name: Analyze generated container
        run: cd example && dart run build_runner build --delete-conflicting-outputs && cd .. &&  dart analyze example

      - name: Set permissions
        run: chmod +x run_tests.sh

      - name: Run tests
        run: ./run_tests.sh ${{ secrets.REPO_TOKEN }}
