name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_catalyst_builder:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/catalyst_builder

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: dart analyze lib

      - name: Analyze generated container
        run: cd example && dart run build_runner build --delete-conflicting-outputs && cd .. &&  dart analyze example

      - name: Set permissions
        run: chmod +x run_tests.sh

      - name: Run tests
        run: ./run_tests.sh
  test_catalyst_builder_contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/catalyst_builder_contracts

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: dart analyze lib

      - name: Run tests
        run: dart test
  test_catalyst_builder_container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/catalyst_builder_container

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: dart analyze lib

      - name: Run tests
        run: dart test
